/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/utils/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
            extend: {
                fontFamily: {
                sans: ["var(--font-inter)", "sans-serif"],
                },
                colors: {
                    // Primary: Fertile Soil 
                    primary: {
                        DEFAULT: '#8b5e3c',
                        10: '#7d5536',
                        20: '#6f4b30',
                        30: '#61422a',
                        40: '#533824',
                        50: '#462f1e',
                        60: '#382618',
                        70: '#2a1c12',
                        80: '#1c120c',
                        90: '#0e0906',
                    },
                    // Secondary: Mother of Pearl
                    secondary: {
                        DEFAULT: '#ead7c5',
                        10: '#d3c2b1',
                        20: '#bbac9e',
                        30: '#a4978a',
                        40: '#8c8176',
                        50: '#756c63',
                        60: '#5e564f',
                        70: '#46413b',
                        80: '#2f2b27',
                        90: '#171614',
                    },
                    // Additional: Scallion (Green)
                    accent: {
                        DEFAULT: '#6b8e23',
                        10: '#608020',
                        20: '#56721c',
                        30: '#4b6319',
                        40: '#405515',
                        50: '#364712',
                        60: '#2b390e',
                        70: '#202b0b',
                        80: '#151c07',
                        90: '#0b0e04',
                    },
                },
                spacing: {
                    '1': '4px',
                    '1.5': '6px',
                    '2': '8px',
                    '2.5': '10px',
                    '3': '12px',
                    '3.5': '14px',
                    '4': '16px',
                    '5': '20px',
                    '6': '24px',
                    '7': '28px',
                    '8': '32px',
                    '9': '36px',
                    '10': '40px',
                    '11': '44px',
                    '12': '48px',
                    '14': '56px',
                    '16': '64px',
                    '20': '80px',
                    '24': '96px',
                    '28': '112px',
                    '32': '128px',
                    '36': '144px',
                    '40': '160px',
                    '44': '176px',
                    '48': '192px',
                    '52': '208px',
                    '56': '224px',
                    '60': '240px',
                    '64': '256px',
                    '72': '288px',
                    '80': '320px',
                    '96': '384px',
                },
                // Typography
                fontSize: {
                    'h1': ['70px', { lineHeight: '48px', fontWeight: '900' }],
                    'h2': ['45px', { lineHeight: '40px', fontWeight: '900' }],
                    'h3': ['30px', { lineHeight: '36px', fontWeight: '900' }],
                    'h4': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                    'text-lg': ['18px', { lineHeight: '28px' }],
                    'base': ['16px', { lineHeight: '24px' }],
                    'text-sm': ['14px', { lineHeight: '20px' }],
                    'text-xs': ['12px', { lineHeight: '16px' }],
                },
            },
        },
    plugins: [],
}